sudo: true
dist: trusty
#group: deprecated-2017Q3
language: python
python:
  - "3.6"
# install pg_chameleon
install: "pip install ."

services:
  - mysql

addons:
  postgresql: "11"
   apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart

before_script:
 - tests/setup_db.sh
 
 # command to run tests
script: tests/test.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/166d0e880973f957205f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

